CREATE TABLE `persons` (
`Id` int(10) UNSIGNED NULL DEFAULT NULL,
`Nome` VARCHAR(50) NULL DEFAULT NULL,
`Sobrenome` VARCHAR(50) NULL DEFAULT NULL,
`Endereco` VARCHAR(50) NULL DEFAULT NULL,
`Genero` VARCHAR(50) NULL DEFAULT NULL
)
ENGINE=InnoDB
;

ALTER TABLE PERSONS CHANGE ID ID INT(10) AUTO_INCREMENT PRIMARY KEY;